[package]
name = "scr"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
slab = "0.4.12"
bitflags = "2.13.1"
libc = "0.2"
scr-macros = { path = "../scr-macros" }
getrandom = "0.4.3"

[dev-dependencies]
hyper = { version = "1.11.1", default-features = false, features = ["server", "http1"] }

# pin-project-lite = "0.2.11"
# tracing
# backtrace
# signal-hook-registry
# socket2